### ISSUE TITLE
Was this generated from py_fresh ?

### ISSUE THREAD

**Issue by oke-aditya** [picturate/quickTextCassifier#1]
Looks like it is generated from [py_fresh](https://github.com/oke-aditya/py_fresh).

If yes, then you can add projects made from `py_fresh` in [this](https://github.com/oke-aditya/py_fresh/blob/master/README.md) readme.

Also use latest version, of py_fresh which is much better now with all bugs squashed and ready to release PyPi action.

**Comment by ramaneswaran** [comment]
Thanks for raising the issue
Yes this was generated from an older version of py_fresh
I will incorporate the changes from the latest version
