### ISSUE TITLE
Cite the template creator and sources

### ISSUE THREAD

**Issue by oke-aditya** [picturate/quickTextCassifier#36]
You seem to have taken this template from MWML.

1. Please cite it (if this was pvt / presonal repo I wouldn't have said but this belongs to @GDGVIT)
2. Edit the email address. MWML is not responsible for any such communication.

P.S. I thought it belonged to @picturate which would be fine to use this template (after citing) etc.
But for @GDGVIT I would recommend using a template which this organization may provide (if they).
Else cite the sources ! This template is MIT Licensed so feel free to use it.

**Comment by L04DB4L4NC3R** [comment]
> You seem to have taken this template from MWML.
> 
>     1. Please cite it (if this was pvt / presonal repo I wouldn't have said but this belongs to @GDGVIT)
> 
>     2. Edit the email address. MWML is not responsible for any such communication.
> 
> 
> P.S. I thought it belonged to @picturate which would be fine to use this template (after citing) etc.
> But for @GDGVIT I would recommend using a template which this organization may provide (if they).
> Else cite the sources ! This template is MIT Licensed so feel free to use it.

Thank you for noticing this. Will add the citation shortly

**Comment by oke-aditya** [comment]
Also edit [contributing.md](https://github.com/GDGVIT/quicktext/blob/master/CONTRIBUTING.md) file seems like this template has come from [my ](https://github.com/oke-aditya/py_fresh) repo. Hopefully you cite that as well.

**Comment by searchformyusername** [comment]
@ramaneswaran use templates, coc, contributing.md provided in https://github.com/GDGVIT/template

I see it's assigned to me, I will do it.

**Comment by ramaneswaran** [comment]
@1UC1F3R616 thanks

**Comment by searchformyusername** [comment]
@oke-aditya , I have made the changes. Kindly close the issue if these are satisfactory enough.

Refernce: https://github.com/GDGVIT/quicktext/pull/37
- thanks, kush

**Comment by searchformyusername** [comment]
@oke-aditya can this be closed now?

References: https://github.com/oke-aditya/py_fresh/pull/20
https://github.com/GDGVIT/quicktext/pull/37
